### PR TITLE
Numpy Section Rewrite

### PR DESCRIPTION
**Pull request by anthonyduer**
Rewrote the section on NumPy to make it more comprehensive and thorough. Included several new examples of code and discussed datatypes and two new reference. :)

### CODE REVIEW

**Comment by anthonyduer** [comment]
@tbalson Hey Tyler - would you mind reviewing my NumPy rewrite? I removed the eig() and diag() functions from the Linear Algebra section but can add them back in, if necessary. I had assumed they were a bit specific for a short section.

**Comment by laszewsk** [comment]
you need to add all deleted examples if they are not improved by other examples you did.
Also its unclear if now the examples are plagerized by you, so you need to verify this with the original source, and if they are create new examples

**Comment by anthonyduer** [comment]
I've added all of the examples I removed back into the section - sorry about that!

For the new examples, obviously I don't want to plagiarize, but I'm not certain how to prove it - I generated the examples in Python by myself using NumPy using fairly nondescript sequences of numbers (1, 2, 3...) for the most part.

**Comment by laszewsk** [comment]
tyler please review and let me know if we can/should approve

**Comment by laszewsk** [comment]
can you check that no examples were lost

**Comment by anthonyduer** [comment]
I've updated the grammar, mixed some spelling errors, and proofread the section again - sorry about the grammatical errors. I'll try and pull things into Word/Google Docs rather than editing directly in GitHub to avoid the issue in the future.

**Comment by tbalson** [comment]
Original examples enhanced/retained.

**Comment by tbalson** [comment]
We need to discuss relevant uses for eig and diag instead of just having them at the end. We can create an issue for this as it has enough substance be be another section...maybe on ML for IP with scikit learn.

**Comment by anthonyduer** [comment]
> We need to discuss relevant uses for eig and diag instead of just having them at the end. We can create an issue for this as it has enough substance be be another section...maybe on ML for IP with scikit learn.

Agreed - they were there in the original and I kept them at the professor's request but they felt a little out-of-place in the original version.

**Comment by laszewsk** [comment]
eig and diag are good examples of funtions beyond trivial mean and so on.

**Pull request merged**
