### PR TITLE
Added images and sections for data exploration in machine learning 

### PR DESCRIPTION
**Pull request by manjunathsivan**

### CODE REVIEW

**Comment by laszewsk** [comment]
please resolve the conflict,

**Comment by laszewsk** [comment]
you seem to striggle with the pull request. you have created yourself conflicts in your own pull request. Please resolve.

**Comment by manjunathsivan** [comment]
hi Prof,  
Yah on the file name there was a issue since my forked branch had older name. I have corrected the same now. Also the python indentation I have corrected now. Please check and let me know in case you see any indentation issues.

**Comment by laszewsk** [comment]
lets see if it passes. its working at this time 

https://github.com/cloudmesh-community/book/pull/389#issuecomment-467702745

the workflow check will hopefully be green in a couple minuts, if not, I suggest you change what is reported in tetails.

**Comment by manjunathsivan** [comment]
hi Prof, 
   Completed the spell check...all typo mistakes have been corrected.
Regards
Manjunath Sivan

**Pull request merged**
