### PR TITLE
Chapter AI service with REST

### PR DESCRIPTION
**Pull request by mallik3006**
Chapter submission - AI service with REST.

https://github.com/cloudmesh-community/book/issues/243

### CODE REVIEW

**Comment by laszewsk** [comment]
Tyler please review ASAP, as you may have worked on an equivalent section that you introduced as this section was apparently not yet ready when you finished yours.

**Comment by laszewsk** [comment]
I have not yet accepted this

**Comment by mallik3006** [comment]
> things such as
> 
> ``python
> pip install --upgrade google-cloud-vision
> 
> ```
> 
> must be
> 
> ``bash
> $ pip install --upgrade google-cloud-vision
> ```

**Comment by mallik3006** [comment]
> things such as
> 
> ``python
> pip install --upgrade google-cloud-vision
> 
> ```
> 
> must be
> 
> ``bash
> $ pip install --upgrade google-cloud-vision
> ```

I have made changes in all the applicable places.

**Comment by mallik3006** [comment]
> figure shows: @fig:GCV-KEY
> 
> remember that a @fig:GCV-KEY will be replaced with
> 
> Figure xyz
> 
> so you need to rewrite your centences
> 
> ALso the label is the one starting with fig: e.g. the one in {} at the end of the line

Apologies, I misunderstood the labels of the figure, thank you for clarification. 
I updated all the sentences and referred to the appropriate label names.

**Comment by mallik3006** [comment]
> titles in bibtex are wrong.

I updated the titles appropriately, please let me know if they look fine.

**Comment by mallik3006** [comment]
Accidentally closed it, reopening the Pull request.

**Comment by mallik3006** [comment]
> make sure to add the bibtex entries and refer to them,

I believe this is reference to the following:

use also bibtex for things such as

here.

Actually, the link above is my azure storage account where I uploaded the datasets to and made available. I'm reusing the datasets I have with me which have been used for my learning earlier. In this case, how do you want me to reference these?

**Comment by mallik3006** [comment]
> > make sure to add the bibtex entries and refer to them,
> 
> I believe this is reference to the following:
> 
> use also bibtex for things such as
> 
> here.
> 
> Actually, the link above is my azure storage account where I uploaded the datasets to and made available. I'm reusing the datasets I have with me which have been used for my learning earlier. In this case, how do you want me to reference these?
> 
> Did you generate the dataset by yourself or where did you get it from?

I took one of my course assignments' input datasets and I modified the training dataset for simplifying the example. I'm not aware of the original source of the dataset.

**Comment by tbalson** [comment]
I am accepting this however I have a few remarks to think about that could make this a bit more complete see the following comments: 

Does google tell us what is happening under the hood? If you could discuss some pitfalls of this service that would be beneficial, like find some more images and see if you get any labels that do not make sense and discuss for example what is a "hill station" in your current example is that a correct label for this image? Is it on a hill?

for the naive bayes implementation it would be cool to implement a post so the user can add a new review of the restaurant we can work on this together. We also want to implement the naive bayes portion in the cloudmesh framework as i do not have this implemented in the ML portion of the cloudmesh framework yet. 

(I will create an issue with other students working on ML so we can coordinate integration into the cm framework)

**Pull request merged**
