### PR TITLE
Updates to Chapter - AI with REST and added Section - HTML with Beautiful Soup 

### PR DESCRIPTION
**Pull request by mallik3006**
Made changes for the following review comments:

⭕️ bibs missning

⭕️ terms usch as GOOGLE_APPLICATION_CREDENTIALS should be GOOGLE_APPLICATION_CREDENTIALS

⭕️ could screenshots bee redone on windows that are less wide with larger font, quality is bad due to unneded space

### CODE REVIEW

**Comment by mallik3006** [comment]
Added content related to HTML accessing with Beautiful Soup

**Comment by mallik3006** [comment]
> why is the citation removed?

There is a mention of the direct link at the start of the section, I was not sure if it needed a citation again. I can add it back if required. Please let me know.

**Comment by laszewsk** [comment]
please review plagarism rules, if you cite from a source you still need a citation. it is not sufficient to just introduce a link at the beginning. however you wrote the section i guess so its your call, but you must adhere to the rules.

**Comment by mallik3006** [comment]
> please review plagarism rules, if you cite from a source you still need a citation. it is not sufficient to just introduce a link at the beginning. however you wrote the section i guess so its your call, but you must adhere to the rules.

I included the bib, please review.

**Comment by mallik3006** [comment]
> regular athors have only one {} and not {{}} late is for things that do not have firstname lastname
> 
> Package is caps

Updated the bib.

**Pull request merged**
