### PR TITLE
Moved amazon-emr-2.md

### PR DESCRIPTION
**Pull request by tvangalapat**
Moved/merged amazon-emr-2.md to emr1 due to duplicate effort

### CODE REVIEW

**Comment by tvangalapat** [comment]
I am trying to add content to emr1, when i did that and create a pull request is failed to pass integration

**Comment by laszewsk** [comment]
the workflow and my comment showed what is wrong, work with TA

**Comment by laszewsk** [comment]
it is unclear if this pull request has been covered through another one, if so this pull request needs to be removed

**Comment by tbalson** [comment]
keeping this one open: https://github.com/cloudmesh-community/book/pull/439

**Pull request closed without merging**
