### PR TITLE
edit all files, cleaned .bib, corrected references

### PR DESCRIPTION
**Pull request by keithhickman08**

### CODE REVIEW

**Comment by laszewsk** [comment]
i can ot check as document does not compile

**Comment by laszewsk** [comment]
niranda, work with student. I amunfortuantely out of time to help on bibtex.

**Comment by keithhickman08** [comment]
Niranda - here's the error message from the github build: 

[WARNING] Duplicate identifier 'sec:swagger-verify' at line 4298 column 1
Error reading bibliography /root/project/books/cloud/dest/all.bib (line 1535, column 5):
unexpected "k"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
mv dest/vonLaszewski-cloud.epub ../../docs
mv: cannot stat 'dest/vonLaszewski-cloud.epub': No such file or directory
make: *** [Makefile:12: epub] Error 1
Exited with code 2

I didn't modify the swagger-verify file. Any help is appreciated. I'm on slack in the cloudmesh channel. Any help is appreciated.

**Comment by laszewsk** [comment]
your bibtex is not properly formatted, for example, you can not put newlines into a url, that is kind of logical. SPo make sure your bibtex follows common sense rules.

**Comment by laszewsk** [comment]
also make sure you are up to date with what is in github. I fixed previously errors in your bibtex file but you neeed to make sure that you stay in sync

**Comment by laszewsk** [comment]
I will now try to play with this but likeley regret it as this all can be done on your system before you check in ...

**Comment by laszewsk** [comment]
Keith:

I think you need to get used to the fact that you MUST 
compile your contributions locally.  You do not even check the syntax of your bibfiles, nor do you use either emacs or jabref to validate them. It is obvious from the following. 

PLEASE PLEASE USE OUR RECOMMENDED TOOLS! THis is just logical

@Misc{www-essenciary,
    month = sep,
    year = 2019,
    author = {Adrian Salceanu}
    key = {Genie.jl}
    title = {Genie: The highly productive Julia web framework}
    howpublished = {Code Repository}
    url = {<https://github.com/essenciary/Genie.jl}
}

why

**Comment by keithhickman08** [comment]
Sorry for the frustration Gregor! It looks like the pull request has been merged.  I did re-validate the .bib and the .md files with jabref, pandoc, and overleaf. Apologies again.

**Pull request merged**
