### PR TITLE
Create terraform.md

### PR DESCRIPTION
**Pull request by joshish-iu**

### CODE REVIEW

**Comment by joshish-iu** [comment]
Updated as per comments - changed headings, updated text to remove questions, added proper formatting

**Comment by joshish-iu** [comment]
Should I delete the conflicting file (chapters/devops/iac-terraform.md) ? This was the old name. Now this file got split into devops-iac.md (tracked by a separate pull request) and terraform.md.

**Comment by laszewsk** [comment]
suggestion:

a) make backup
b) delete this pull request
c) update files in teh new locations
d) create new pull requests as needed.

As we want you to do your best you are in charge. E.g. we do not want to delete somthing you do not want to delete. That is somoething you need to decide.

**Comment by joshish-iu** [comment]
Deleting pull request due to conflict.

**Pull request closed without merging**
