### PR TITLE
updated scikit learn.md and images folder

### PR DESCRIPTION
**Pull request by manjunathsivan**

### CODE REVIEW

**Comment by laszewsk** [comment]
There are conflicts that you need to fix

**Comment by manjunathsivan** [comment]
Conflicts have been resolved

**Comment by laszewsk** [comment]
Tyler review and correct his ASAP. THis will be in generla helpful. However as you also work on this in parallel. Its important you review. biggest concern i had was the regression section, that was removed, whihc i am not sure if you use that in class

**Comment by laszewsk** [comment]
other things are 2 sections with a single #
cations shoudl not be one word
some illegal ====

**Comment by tbalson** [comment]
This is good. I think we should have some sample code for each ML section i.e. linear regression, logistic regression, etc etc. I think I will merge this and we can create an issue for either  @manjunathsivan to add some code examples or for other students to contribute further.  Or maybe we should have examples in the cloudmesh.nn framework and reference the framework from the chapter to see examples. Let me think about this, in the mean time @manjunathsivan have you fixed the .md issues and citations?

**Comment by tbalson** [comment]
Will create issues for example code.

**Comment by manjunathsivan** [comment]
hi , 
   I have fixed the citation issues. Also added sample code for Linear, Logistic, Random forest, decision tree and K -means Machine learning model.
Created a pull request 
https://github.com/cloudmesh-community/book/pull/412
Regards
Manjunath Sivan

**Pull request merged**
